# Generated by Django 5.2 on 2025-05-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products_image/'),
        ),
    ]
