# Generated by Django 5.2 on 2025-05-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_image'),
        ('purchases', '0002_purchase_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='image',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='المنتج'),
        ),
    ]
