# Generated by Django 5.2 on 2025-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchase_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='product_new',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='منتج جديد'),
        ),
    ]
